// Mock data for the Farm Management System

export const mockStats = {
    totalTasks: 24,
    completedTasks: 18,
    activeCropCycles: 3,
    totalIncome: 145000,
    totalExpense: 78000,
    pendingOrders: 7,
    eligibleSchemes: 4,
    walletBalance: 67000,
};

export const mockTasks = [
    {
        id: 1,
        title: "Apply Fertilizer to Wheat Field",
        category: "Crop Cycle",
        cropCycle: "Winter Wheat 2024",
        dueDate: "2025-10-08",
        status: "pending",
        progress: 0,
        cost: 5000,
        priority: "high",
        description: "Apply fertilizer to wheat field before the expected rain",
    },
    {
        id: 2,
        title: "Check Irrigation System",
        category: "Crop Cycle",
        cropCycle: "Rice Paddy 2024",
        dueDate: "2025-10-07",
        status: "in-progress",
        progress: 60,
        cost: 2000,
        priority: "medium",
        description: "Regular maintenance check for irrigation system",
    },
    {
        id: 3,
        title: "Order Seeds for Next Season",
        category: "General",
        dueDate: "2025-10-15",
        status: "pending",
        progress: 0,
        cost: 15000,
        priority: "low",
        description: "Order seeds for upcoming planting season",
    },
    {
        id: 4,
        title: "Harvest Tomatoes",
        category: "Crop Cycle",
        cropCycle: "Tomato Field A",
        dueDate: "2025-10-06",
        status: "completed",
        progress: 100,
        cost: 8000,
        priority: "high",
        description: "Harvest ripe tomatoes from Field A",
    },
    {
        id: 5,
        title: "Pest Control Treatment",
        category: "Crop Cycle",
        cropCycle: "Winter Wheat 2024",
        dueDate: "2025-10-10",
        status: "pending",
        progress: 0,
        cost: 3500,
        priority: "high",
        description: "Apply pest control treatment to prevent infestation",
    },
];

export const mockCropCycles = [
    {
        id: 1,
        name: "Winter Wheat 2024",
        variety: "HD-2967",
        status: "in-progress",
        sowingDate: "2024-11-15",
        expectedHarvest: "2025-04-20",
        totalArea: 5,
        progress: 45,
        profit: 35000,
        loss: 0,
    },
    {
        id: 2,
        name: "Rice Paddy 2024",
        variety: "Basmati 1121",
        status: "in-progress",
        sowingDate: "2024-07-01",
        expectedHarvest: "2025-11-15",
        totalArea: 8,
        progress: 70,
        profit: 85000,
        loss: 0,
    },
    {
        id: 3,
        name: "Tomato Field A",
        variety: "Hybrid Roma",
        status: "completed",
        sowingDate: "2024-08-10",
        expectedHarvest: "2024-12-05",
        totalArea: 2,
        progress: 100,
        profit: 45000,
        loss: 5000,
    },
];

export const mockTransactions = [
    {
        id: 1,
        date: "2025-10-05",
        type: "income",
        category: "Product Sale",
        amount: 25000,
        description: "Tomato sales to vendor",
        relatedTo: "Order #1234",
    },
    {
        id: 2,
        date: "2025-10-04",
        type: "expense",
        category: "Seeds",
        amount: 15000,
        description: "Seeds purchase",
        relatedTo: "Task #3",
    },
    {
        id: 3,
        date: "2025-10-03",
        type: "income",
        category: "Product Sale",
        amount: 18000,
        description: "Wheat sales",
        relatedTo: "Order #1230",
    },
    {
        id: 4,
        date: "2025-10-02",
        type: "expense",
        category: "Fertilizer",
        amount: 8000,
        description: "Fertilizer purchase",
        relatedTo: "Task #1",
    },
    {
        id: 5,
        date: "2025-10-01",
        type: "expense",
        category: "Labor",
        amount: 12000,
        description: "Labor wages",
        relatedTo: "-",
    },
];

export const mockProducts = [
    {
        id: 1,
        name: "Organic Wheat",
        category: "Grains",
        price: 2500,
        unit: "quintal",
        quantity: 50,
        status: "Available",
        farmer: "Rajesh Kumar",
        farmerId: 1,
        rating: 0,
        reviews: 0,
        image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400",
    },
    {
        id: 2,
        name: "Basmati Rice",
        category: "Grains",
        price: 4500,
        unit: "quintal",
        quantity: 35,
        status: "Available",
        farmer: "Priya Singh",
        farmerId: 2,
        rating: 0,
        reviews: 0,
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400",
    },
    {
        id: 3,
        name: "Fresh Tomatoes",
        category: "Vegetables",
        price: 40,
        unit: "kg",
        quantity: 500,
        status: "Available",
        farmer: "Rajesh Kumar",
        farmerId: 1,
        rating: 0,
        reviews: 0,
        image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400",
    },
    {
        id: 4,
        name: "Organic Potatoes",
        category: "Vegetables",
        price: 30,
        unit: "kg",
        quantity: 300,
        status: "Available",
        farmer: "Amit Patel",
        farmerId: 3,
        rating: 0,
        reviews: 0,
        image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400",
    },
    {
        id: 5,
        name: "Fresh Carrots",
        category: "Vegetables",
        price: 35,
        unit: "kg",
        quantity: 200,
        status: "Available",
        farmer: "Priya Singh",
        farmerId: 2,
        rating: 0,
        reviews: 0,
        image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400",
    },
    {
        id: 6,
        name: "Organic Onions",
        category: "Vegetables",
        price: 25,
        unit: "kg",
        quantity: 400,
        status: "Available",
        farmer: "Amit Patel",
        farmerId: 3,
        rating: 0,
        reviews: 0,
        image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400",
    },
];

export const mockOrders = [
    {
        id: 1,
        buyer: "ABC Traders Ltd",
        product: "Organic Wheat",
        quantity: "20 quintals",
        totalAmount: 50000,
        status: "pending",
        date: "2025-10-05",
        paymentStatus: "unpaid",
        buyerEmail: "contact@abctraders.com",
        buyerPhone: "+91 98765 43210",
    },
    {
        id: 2,
        buyer: "Green Market Co",
        product: "Fresh Tomatoes",
        quantity: "200 kg",
        totalAmount: 8000,
        status: "delivered",
        date: "2025-10-03",
        paymentStatus: "paid",
        buyerEmail: "info@greenmarket.com",
        buyerPhone: "+91 98765 43211",
    },
    {
        id: 3,
        buyer: "XYZ Exports",
        product: "Basmati Rice",
        quantity: "15 quintals",
        totalAmount: 67500,
        status: "in-transit",
        date: "2025-10-02",
        paymentStatus: "paid",
        buyerEmail: "exports@xyz.com",
        buyerPhone: "+91 98765 43212",
    },
];

export const mockWeather = {
    current: {
        location: "Punjab, India",
        temp: 28,
        condition: "Partly Cloudy",
        humidity: 65,
        windSpeed: 12,
    },
    forecast: [
        { day: "Tomorrow", temp: 29, condition: "Sunny", icon: "sun" },
        { day: "Wednesday", temp: 27, condition: "Cloudy", icon: "cloud" },
        { day: "Thursday", temp: 25, condition: "Rain", icon: "cloud-rain" },
    ],
    alerts: [
        {
            type: "warning",
            message: "Heavy rainfall expected on Thursday. Prepare drainage systems.",
        },
    ],
};

export const mockSchemes = [
    {
        id: 1,
        name: "PM-KISAN Scheme",
        description: "Direct income support of ₹6000 per year in three equal installments to all landholding farmers' families",
        eligible: true,
        status: "enrolled",
        amount: "₹6,000/year",
        deadline: "2025-12-31",
        eligibility: "All landholding farmers irrespective of size of their land holdings",
        link: "https://pmkisan.gov.in/",
    },
    {
        id: 2,
        name: "Soil Health Card Scheme",
        description: "Free soil testing and health card to promote judicious use of fertilizers and improve soil health",
        eligible: true,
        status: "available",
        amount: "Free Service",
        deadline: "2025-11-30",
        eligibility: "All farmers with agricultural land",
        link: "https://soilhealth.dac.gov.in/",
    },
    {
        id: 3,
        name: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        description: "Comprehensive crop insurance at subsidized premium rates to safeguard farmers against crop loss",
        eligible: true,
        status: "available",
        amount: "Premium subsidy up to 90%",
        deadline: "2025-10-31",
        eligibility: "All farmers including sharecroppers and tenant farmers",
        link: "https://pmfby.gov.in/",
    },
    {
        id: 4,
        name: "Kisan Credit Card (KCC)",
        description: "Low interest credit for farming needs including seeds, fertilizers, and working capital",
        eligible: true,
        status: "enrolled",
        amount: "Credit limit up to ₹3 lakh",
        deadline: "Open enrollment",
        eligibility: "All farmers engaged in agriculture and allied activities",
        link: "https://www.nabard.org/content1.aspx?id=574&catid=23&mid=530",
    },
    {
        id: 5,
        name: "PM Kusum Yojana",
        description: "Financial support for installation of solar pumps and grid connected solar power plants",
        eligible: true,
        status: "available",
        amount: "Subsidy up to 60%",
        deadline: "2026-03-31",
        eligibility: "Individual farmers and farmer groups",
        link: "https://pmkusum.mnre.gov.in/",
    },
    {
        id: 6,
        name: "National Agriculture Market (e-NAM)",
        description: "Online trading platform for agricultural commodities to get better prices",
        eligible: false,
        status: "available",
        amount: "Free platform access",
        deadline: "Ongoing",
        eligibility: "Farmers registered at e-NAM mandis",
        link: "https://www.enam.gov.in/",
    },
    {
        id: 7,
        name: "Pradhan Mantri Kisan Maan Dhan Yojana",
        description: "Pension scheme for small and marginal farmers ensuring old age protection",
        eligible: false,
        status: "available",
        amount: "₹3,000/month pension after 60 years",
        deadline: "Open enrollment",
        eligibility: "Small and marginal farmers aged 18-40 years",
        link: "https://maandhan.in/",
    },
    {
        id: 8,
        name: "Agriculture Infrastructure Fund",
        description: "Medium to long-term debt financing for investment in post-harvest management",
        eligible: false,
        status: "available",
        amount: "Loans up to ₹2 crore",
        deadline: "2025-12-31",
        eligibility: "Farmers, FPOs, cooperatives, and agri-entrepreneurs",
        link: "https://www.nabard.org/content1.aspx?id=1775&catid=8&mid=560",
    },
];

export const mockNotifications = [
    {
        id: 1,
        type: "task",
        title: "Task Due Soon",
        message: "Check Irrigation System is due tomorrow",
        timestamp: "2 hours ago",
        read: false,
    },
    {
        id: 2,
        type: "weather",
        title: "Weather Alert",
        message: "Heavy rainfall expected on Thursday",
        timestamp: "4 hours ago",
        read: false,
    },
    {
        id: 3,
        type: "payment",
        title: "Payment Received",
        message: "₹25,000 received from ABC Traders Ltd",
        timestamp: "1 day ago",
        read: true,
    },
    {
        id: 4,
        type: "system",
        title: "New Scheme Available",
        message: "You're eligible for Soil Health Card Scheme",
        timestamp: "2 days ago",
        read: true,
    },
];

export const chartData = {
    taskProgress: [
        { name: "Completed", value: 18, fill: "#4CAF50" },
        { name: "Pending", value: 6, fill: "#FFA726" },
    ],
    financialSummary: [
        { month: "May", income: 120000, expense: 65000 },
        { month: "Jun", income: 135000, expense: 72000 },
        { month: "Jul", income: 110000, expense: 68000 },
        { month: "Aug", income: 125000, expense: 70000 },
        { month: "Sep", income: 140000, expense: 75000 },
        { month: "Oct", income: 145000, expense: 78000 },
    ],
    cropProgress: [
        { name: "Winter Wheat", progress: 45 },
        { name: "Rice Paddy", progress: 70 },
        { name: "Tomato Field", progress: 100 },
    ],
};

// Ratings given to farmers by buyers
export const mockFarmerRatings = [
    {
        id: 1,
        buyerName: "ABC Traders Ltd",
        rating: 0,
        comment: "Excellent quality products! Always delivers on time.",
        date: "2025-10-05",
        orderProduct: "Organic Wheat - 20 quintals",
    },
    {
        id: 2,
        buyerName: "Green Market Co",
        rating: 0,
        comment: "Good service and fresh produce. Highly recommended.",
        date: "2025-10-03",
        orderProduct: "Fresh Tomatoes - 200 kg",
    },
    {
        id: 3,
        buyerName: "XYZ Exports",
        rating: 0,
        comment: "Outstanding quality basmati rice. Will order again!",
        date: "2025-10-02",
        orderProduct: "Basmati Rice - 15 quintals",
    },
];

// Ratings given to buyers by farmers
export const mockBuyerRatings = [
    {
        id: 1,
        buyerName: "ABC Traders Ltd",
        rating: 0,
        comment: "Prompt payment and professional communication.",
        date: "2025-10-05",
        product: "Organic Wheat",
    },
    {
        id: 2,
        buyerName: "Green Market Co",
        rating: 0,
        comment: "Reliable buyer. Good business partner.",
        date: "2025-10-03",
        product: "Fresh Tomatoes",
    },
];

// Finances data
export const mockFinances = [
    {
        id: 1,
        type: "income",
        category: "Product Sale",
        amount: 25000,
        date: "2025-10-05",
        description: "Tomato sales to vendor",
        paymentMethod: "Bank Transfer",
    },
    {
        id: 2,
        type: "expense",
        category: "Seeds",
        amount: 15000,
        date: "2025-10-04",
        description: "Seeds purchase",
        paymentMethod: "Cash",
    },
    {
        id: 3,
        type: "income",
        category: "Product Sale",
        amount: 18000,
        date: "2025-10-03",
        description: "Wheat sales",
        paymentMethod: "UPI",
    },
    {
        id: 4,
        type: "expense",
        category: "Fertilizer",
        amount: 8000,
        date: "2025-10-02",
        description: "Fertilizer purchase",
        paymentMethod: "Cash",
    },
    {
        id: 5,
        type: "expense",
        category: "Labor",
        amount: 12000,
        date: "2025-10-01",
        description: "Labor wages",
        paymentMethod: "Cash",
    },
];

// Buyers data
export const mockBuyers = [
    {
        id: 1,
        name: "ABC Traders Ltd",
        email: "contact@abctraders.com",
        phone: "+91 98765 43210",
        location: "Mumbai, Maharashtra",
        joinedDate: "2024-01-15",
        totalOrders: 24,
        totalSpent: 450000,
        status: "active",
    },
    {
        id: 2,
        name: "Green Market Co",
        email: "info@greenmarket.com",
        phone: "+91 98765 43211",
        location: "Delhi, NCR",
        joinedDate: "2024-03-20",
        totalOrders: 18,
        totalSpent: 320000,
        status: "active",
    },
    {
        id: 3,
        name: "XYZ Exports",
        email: "exports@xyz.com",
        phone: "+91 98765 43212",
        location: "Bangalore, Karnataka",
        joinedDate: "2024-05-10",
        totalOrders: 32,
        totalSpent: 680000,
        status: "active",
    },
    {
        id: 4,
        name: "Fresh Foods Inc",
        email: "hello@freshfoods.com",
        phone: "+91 98765 43213",
        location: "Pune, Maharashtra",
        joinedDate: "2024-07-05",
        totalOrders: 12,
        totalSpent: 180000,
        status: "inactive",
    },
];

// Farmers data
export const mockFarmers = [
    {
        id: 1,
        name: "Rajesh Kumar",
        email: "rajesh.kumar@farm.com",
        phone: "+91 98765 12345",
        location: "Punjab",
        farmSize: "15 acres",
        joinedDate: "2023-08-15",
        totalProducts: 12,
        totalRevenue: 850000,
        status: "active",
    },
    {
        id: 2,
        name: "Priya Singh",
        email: "priya.singh@farm.com",
        phone: "+91 98765 12346",
        location: "Haryana",
        farmSize: "22 acres",
        joinedDate: "2023-09-20",
        totalProducts: 18,
        totalRevenue: 1200000,
        status: "active",
    },
    {
        id: 3,
        name: "Amit Patel",
        email: "amit.patel@farm.com",
        phone: "+91 98765 12347",
        location: "Gujarat",
        farmSize: "10 acres",
        joinedDate: "2024-01-10",
        totalProducts: 8,
        totalRevenue: 450000,
        status: "active",
    },
    {
        id: 4,
        name: "Sunita Devi",
        email: "sunita.devi@farm.com",
        phone: "+91 98765 12348",
        location: "Uttar Pradesh",
        farmSize: "18 acres",
        joinedDate: "2024-03-05",
        totalProducts: 14,
        totalRevenue: 720000,
        status: "inactive",
    },
];
